### ISSUE TITLE
Perfomance testing of Solana

### ISSUE THREAD

**Issue by cyberadmin** [cybercongress/cyberd#10]

**Comment by hleb-albau** [comment]
Current multi-node tests (release 0.6.0):
- Using Mars as Leader node
- Use my pc as second node( akka validator) and client
- Using local network. Using iperf, measured  local network bandwidth  - 17Mbit/sec.

Results:
1. For default client test with 500k tx I got 50k successful txes (other were dropped due low network)
2. Second node got txes from leader (but in  each batch about 20txes lost somewhere)
3. Tps = 3k tx/s (max current network limit 5k tx/s)

Other notes:
- It's not blockchain right now, just raw services
- There is no consensus
- There is SM machine

It's only beginning of the project. Waiting for next major release (September).

**Comment by xhipster** [comment]
Let get back to a [newer version](https://github.com/solana-labs/solana/releases/tag/v0.7.2)

**Comment by hleb-albau** [comment]
Out of scope of cyberd now.

**Comment by hleb-albau** [comment]
@xhipster  proof-of-history is fake.

**Comment by hleb-albau** [comment]
So, will open a more concrete issue before 0.3.
