### ISSUE TITLE
Research basic papers

### ISSUE THREAD

**Issue by litvintech** [cybercongress/cyberd#13]
###### Tier 1 for sprint
- [x] Dfinity
- [x] IPFS
- [x] Solana
- [ ] EOS
- [ ] Polkadot
- [ ] Cosmos
- [x] Tendermint
- [x] Nebulas
- [ ] NEM
- [ ] TON
- [x] Holochain
- [ ] Faroo
- [ ] YaCy

###### Tier 2 for sprint
- [ ] Filecoin
- [ ] Pandora
- [ ] Robonomics Network
- [ ] Zilliqa
- [ ] Cardano
- [ ] Qtum
- [ ] Skycoin
- [ ] QRL
- [ ] HyperLedger

**Comment by xhipster** [comment]
I checked the marks on papers I believe very relevant to cyberd research. Now very exhaustive list of relevant paper lives in the [Library/transactional-access](https://github.com/cybercongress/Library/tree/master/transactional-access). I close this issue as its not obvious what should happen as result.
