### ISSUE TITLE
Move import_private command to keys subcomand

### ISSUE THREAD

**Issue by xhipster** [cybercongress/cyberd#152]
#### Overview
cyberdcli keys --help do not shows import_private command.

#### Task description

Add `keys import_private` command description to cli help

**Comment by hleb-albau** [comment]
I would rather rename this to **Move import_private command to keys subcomand**.

**Comment by xhipster** [comment]
IMHO it is better to add option to keys add command. Current implementation is confusing

**Comment by hleb-albau** [comment]
Not possible. It is closed, unpluguble peace of code from cosmos :(. That why we create  own separate command.

**Comment by arturalbov** [comment]
It's possible.
Syntax will be `cyberdcli keys add import_private <name>`
