### ISSUE TITLE
Update docker with 0.1.0 version

### ISSUE THREAD

**Issue by xhipster** [cybercongress/cyberd#154]
#### Overview
Current instructions just don't work. We need to update docker image to 0.1.0 release

**Comment by hleb-albau** [comment]
Don't get a point. We should change versioning and naming of releases for docker images?

**Comment by arturalbov** [comment]
@xhipster Please, provide more detailed description.
Currently on docker hub we have two tags `0.1.0` and `euler`, they both actual and working well.
