### ISSUE TITLE
Wrong CYB allocation in Genesis

### ISSUE THREAD

**Issue by xhipster** [cybercongress/cyberd#156]
Allocation for cbd1hlu0kqwvxmhjjsezr00jdrvs2k537mqhrv02ja is 213192777769900 CYB. But I have 3.045611111 CBD at 0x7c4401ae98f12ef6de39ae24cf9fc51f80eba16b address. I suppose that current genesis is wrong

**Comment by xhipster** [comment]
My proposal is to reject an idea of hardfork and just change the allocation to Euler - 0.7%

**Comment by hleb-albau** [comment]
@xhipster I inspect this issue a bit more. 
Our current distribution is 1% for proof of use, and 0.7% for others. 
It still can be okay, but just want to clarify you.
