### ISSUE TITLE
Change token name from CBD to CYB in the testnetwork

### ISSUE THREAD

**Issue by xhipster** [cybercongress/cyberd#157]
First feedback from users shows that it is confusing that we have tokens in different networks with same names. It is also bad decision because according to our distribution plan eventually they will have different value. We need to change the name of the token in our main network so it will not be confusing to humans. CBD - proto substance token, CYB - main token with utility. Also we need to think how to prevent exchanges from listing of CYB tokens.

**Comment by hleb-albau** [comment]
@xhipster 
1.  Could you, please, give some arguments for token name **CYB**. I still think that **CYB** is still confusing and will cause in future a lot of misleading with **cyb** project. We have the project, named **cyb**, and token not related to that project named **CYB**. It is more confusing than now. To fix that issue, we can redeploy erc20 with a different name, and destroy current contract.
2.  Also, we should agree on **cyber** vs **cyberd** names. As far, as I understand, your idea was to name chain as second token **CYBER**. But, currently, we have no idea, how to calculate it. Maybe we should not consider **CYBER**, before getting more research in that field. 

Also, want to get opinions from other players: @Pechalka @asadovka @litvintech @arturalbov

**Comment by arturalbov** [comment]
I'm voting for CBD. IMO, CYB is really confusing name for cyberd token. First that came in mind when I hear CYB - is our browser.

**Comment by asadovka** [comment]
@xhipster @hleb-albau 
seems that we will have enough problems with misunderstanding of projects, tokens and protocols.

In cyb browser there is a reserved app .cyb which stands for system pages and settings. Also, there is an app with controversial name .cyber (which is for search or all protocol functions). If we agree, that, for example, .eth app (ethereum protocol explorer) is valid, . cyb will be responsible for exploring cyberd tokens, which can cause conflicts.

In my opinion, we should reduce the amount of names, that start with "cyb..."

So, for now:

1. CYB - browser name
2. cyberd - protocol name
3. transferable token- CBD, let it be (can be another variant)
4. non-transferable token - another name

**Comment by litvintech** [comment]
I'm voting for CYB for main cyberd's 1st level token
And don't see problems which should confuse users with the cyb browser
The 1st level token is mostly hidden for users in the meaning of economy rather than 2nd level tokens (one of them will be our CYBER). CBD is bootstrapping and transitioning token from Ethereum and there are should be different names for cyberd's 1st and 2nd level tokens.
