### ISSUE TITLE
Get supply

### ISSUE THREAD

**Issue by xhipster** [cybercongress/cyberd#158]
We need to understand how supply is changing over time as well as have a tool to understand its structure. So we need a method that will return current supply value split into 3 categories:
- active balance
- bonding balance
- schrödinger balance

**Comment by arturalbov** [comment]
May be add this info to `index_stats` endpoint? (https://github.com/cybercongress/cyberd/blob/master/docs/rpc.md#index-stats)

**Comment by hleb-albau** [comment]
Now available via 26656/staking/pool endpoint.
