### ISSUE TITLE
CI: Cyberd docker image building. Include genesis file

### ISSUE THREAD

**Issue by arturalbov** [cybercongress/cyberd#160]
Currently when building docker image on CI we have wrong genesis file that is taken from our repository.
In perspective genesis file could be over 100Mbs in size (for now it's about 30Mbs). So better to not store it in repository. We have to upload actual genesis file in cloud (or maybe in IPFS) and download it during docker image building.

**Comment by hleb-albau** [comment]
We can use the same pattern as cosmos does. Just create repo containing testnet files.

**Comment by hleb-albau** [comment]
Also, for the future releases with huge genesis files, it is better to download genesis file during container start.

**Comment by arturalbov** [comment]
IPFS hashes of start configuration files:
Genesis - QmSFTpNaXB3FhB4EWjsrUydupZXTL8Z44c2j18o5CGnN5h
Config - QmdHeSsjkuThTe6VVDD4FUUfpQFH79R8tYrC2bgWwHC2bh
Links - QmepwmLe7vQcK2W6WmvfEk46de3cJ4Jp6jXRXNhuR2AfJ9
