### ISSUE TITLE
Tx size reduction: switch to more compact links tx encoding.

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyberd#171]
A few improvements can be done to radically reduce the size of **link** tx.

1. Use a single msg for a bunch of txes. 
2. Do not duplicate signer for every link. Just use tx signer as the linker.
3. Maybe there is exists more compact encoding of links. For example, cidFrom[cidTo1,cidTo2,cidTo3] instead of cidFromCidTo1cidFromCidTo2cidFromCidTo3.

Todo: Calculate current bytes for tx with single link and N links. Calculate corresponding sizes with 1 and 2 improvements.

**Comment by arturalbov** [comment]
For now implemented 1st and 2d points by PR #192. So, they will be in version 0.1.1
Need to think over point 3. May be move it to separate issue and close this one? 
@hleb-albau What do you think?

**Comment by hleb-albau** [comment]
@arturalbov agreed.

**Comment by arturalbov** [comment]
Closing this one in favor of #212
