### ISSUE TITLE
Infinity race problem.

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyberd#172]
Currently, to sync chain, we need to recalculate all ranks for all heights. That leads us to the problem, where at some network load newcomers nodes may not catch up current state, due to high calculation demand.

**Comment by litvintech** [comment]
@SaveTheAles As I understand it's possible to backup data directory and then start node from backup.
Please check this assumption
https://medium.com/@meleacrypto/cosmos-sdk-how-to-make-one-backup-30abcb153d54

**Comment by litvintech** [comment]
@mrlp4 successfully tested launch from backup, so closing this
