### ISSUE TITLE
Cyberd release scheme.

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyberd#180]
Now, we want to create new intermediate releases. I suggest the next scheme:

**0.** - always 0 till the main net
0.**[0-7]** - our major releases
0.[0-7].**1** - spec changed releases between major releases
0.[0-7].1.**1** - minor changes, such as added RPC endpoint and etc.

**Comment by hleb-albau** [comment]
@xhipster @arturalbov

**Comment by arturalbov** [comment]
@hleb-albau I like that

**Comment by hleb-albau** [comment]
Agreed.
