### ISSUE TITLE
Update cyberd.ai

### ISSUE THREAD

**Issue by xhipster** [cybercongress/cyberd#185]
We need a new paper there :-)

**Comment by asadovka** [comment]
I'll take whitepaper from master branch

**Comment by asadovka** [comment]
[a1essandro11](https://gitcoin.co/profile/a1essandro11) will help with it again

**Comment by asadovka** [comment]
work is almost done, waiting for some fixes in pictures

**Comment by asadovka** [comment]
done

**Comment by asadovka** [comment]
@xhipster please, check the landing
