### ISSUE TITLE
Parse Ethereum network and calculate SpringRank

### ISSUE THREAD

**Issue by litvintech** [cybercongress/cyberd#21]
We need calculate SpringRank for Ethereum
1. make the snapshot of Ethereum network
2. TXs - links, amount - weights
3. calculate SpringRank, calculate the time for rank processing
4. load to any graph db

PS good/faster way to choose python for this
@hleb-albau @arturalbov

**Comment by xhipster** [comment]
@hleb-albau @arturalbov What do you thing about connector to cyber-search?

**Comment by hleb-albau** [comment]
I picked up task.

Next questions right now:
1. About link directions. If **A** sends ETH to **B**, than links direction should be **B** -> **A** ?

**Comment by litvintech** [comment]
@hleb-albau approved PR, googly and correct written comparing with origin paper
Would like to talk with you about iterative rank calculating over new incoming data

**Comment by asadovka** [comment]
currently there is no progress on this task. we do not clearly understand what are the goals of the research.
