### ISSUE TITLE
Mass testing of cyberd-testnet 0.1.1

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyberd#219]
We should test new testnet on CPU and gather all issues and questions.

How to run on CPU:

1. Create cyberd and cyberdcli folders where you want

2. In the command from 3. replace /cyberdata/cyberd-test/cyberd and /cyberdata/cyberd-test/cyberdcli with your path, where folders cyberd and cyberdcli are situated.

3. run this:

docker run -d --name=cyberd-test --restart always \
 -p 26656:26656 -p 26657:26657 -p 26660:26660 \
-e COMPUTE_RANK_ON_GPU=false \
 -v /cyberdata/cyberd-test/cyberd:/root/.cyberd \
 -v /cyberdata/cyberd-test/cyberdcli:/root/.cyberdcli \
 cyberd/cyberd:euler-1.1-dev0

**Comment by asadovka** [comment]
docker exec -ti cyberd cyberdcli tx stake create-validator \
  --amount=100CBD \
  --pubkey=<your_node_pubkey> \
  --moniker=<your_node_nickname> \
  --trust-node \
  --from=<your_key_name> \
  --commission-rate="0.10" \
  --commission-max-rate="0.20" \
  --commission-max-change-rate="0.01" \
  --chain-id=<testnet_chain_id>



in this command for dev 0.1.1 testnet replace tx stake create-validator \ with tx staking create-validator \

**Comment by asadovka** [comment]
@SaveTheAles add info about 1 account can initiate one validator

**Comment by hleb-albau** [comment]
Done!
