### ISSUE TITLE
Losе token on testnet 

### ISSUE THREAD

**Issue by PashaKlybik** [cybercongress/cyberd#227]
Hi!
Me @xhipster send CYB to my address `cbd1lk2j4kkd3fy9rerf9yvae3vjaqxtmn5f5wph0t` it show on cyb browser. After launch 0.1.1 testnet cyb browser show 0.00 CYB. 
@hleb-albau

**Comment by hleb-albau** [comment]
@PashaKlybik did you try @asadovka suggestions?

**Comment by PashaKlybik** [comment]
@hleb-albau, @asadovka  Yes all ok, thank
