### ISSUE TITLE
Add doc of using help feature of cli

### ISSUE THREAD

**Issue by hleb-albau** [cybercongress/cyberd#287]

**Comment by SaveTheAles** [comment]
https://wiki.cybercongress.ai/cyberd/help/ultimate-commands-guide_v2/

**Comment by hleb-albau** [comment]
Nice work man! But, I mean `cyberdcli --help` usage guide.

**Comment by SaveTheAles** [comment]
https://wiki.cybercongress.ai/cyberd/help/ultimate-commands-guide_v2/

I just add `cyberdcli --help` usage guide as a first section in `cybercli gude` is it ok, @hleb-albau ?
