### ISSUE TITLE
Finish Proof of Code genesis drop

### ISSUE THREAD

**Issue by asadovka** [cybercongress/cyberd#294]
### Current Behavior
[comment]: # (Describe what actually happened.)
Currently Proof of Code genesis is 1% of 1%. We need to finish it to avoid misundestandings in team and congress balances.

### Solution

Finish 99% of the drop.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

Updated balances

**Comment by hleb-albau** [comment]
@xhipster assets are under your control as for now.

**Comment by xhipster** [comment]
Now got it.

**Comment by xhipster** [comment]
Irrelevant
