### ISSUE TITLE
Merkle proofs for link storage

### ISSUE THREAD

**Issue by arturalbov** [cybercongress/cyberd#299]
### User Story

The crucial goal of all blockchains is to provide proofs for each entity which impact consensus.
In cyberd - link (along with cid rank) is essential element of whole system. User should have an ability to verify every link that she gets.

### Definition of Done

There is a simple way to implement proofs using current link storage.
It could be done by using `merkle.Tree` in the same way as for CIDs rank. (see https://github.com/cybercongress/cyberd/issues/133)

1. Add `merkle.Tree` field to `LinkIndexedKeeper` structure.
2. Extend `LinkIndexedKeeper.PutLink(...)` method to push marshalled link to merkle tree
3. Extend `LinkIndexedKeeper.Load(...)` method to iterate over all links and push them to tree
4. Add methods to `LinkIndexedKeeper` to provide proofs and get root hash of tree.
5. Add root hash to `CyberdApp.Commit(...)` and `CyberdApp.Info(...)`

**Comment by litvintech** [comment]
@arturalbov @hleb-albau I'm going to put this issue to gitcoin, please, extend user story with the definition of done of this task and any additional information which may be useful to the deal with
