### ISSUE TITLE
Create list of supported and tested GPUs

### ISSUE THREAD

**Issue by litvintech** [cybercongress/cyberd#315]

**Comment by SaveTheAles** [comment]
@litvintech 
https://github.com/cybercongress/cyberd/blob/master/docs/supported_gpu_list.md

**Comment by litvintech** [comment]
@SaveTheAles Please convert it to the table:

|GPU|Supported|Tested|CUDA cores|Year of production|
|-|-|-|-|-|
|NVIDIA GeForce GTX 1050 Ti|:white_check_mark:|:x:|X|2016|

Also add notes about card's memory and knowledage graph

**Comment by SaveTheAles** [comment]
@litvintech 
I think it's done
