### ISSUE TITLE
Add table of seed/validator nodes to README for euler-4

### ISSUE THREAD

**Issue by litvintech** [cybercongress/cyberd#319]
Need to add to README list of seed and validators which provides this seeds. This will allow very fast to setup new nodes by newcomers. 

Note: nodes should expose static IP address and have configured the external address

**Comment by litvintech** [comment]
@SaveTheAles 

|Node ID|IP|Port|Validator|Moniker|Organization|
|--|--|--|--|--|--|
| 472d948cf87f5097244dd52482aa7d45167fc96d | 93.125.26.210 | 34656 | | earth-seed | cyber•Congress |

**Comment by kwunyeung** [comment]
21ae6e8ecad63cecdd190608657c81e99bf499c7@35.197.120.170:26656

**Comment by SaveTheAles** [comment]
34202f6935503da67c07fd89c59e82a5b588c70f@86.57.138.169:33336

**Comment by litvintech** [comment]
@SaveTheAles This task goes to euler-5 after launch

**Comment by mrlp4** [comment]
Some persistent peers: 
f13a5326886c3e251167d433af12fd531a7bc6ee@88.198.36.117:26656
9b1977e4b1102ce3bedff6d8d0bf2adb90d58b9f@195.201.105.229:26656
b34bcaa7536d0f7e09f775d56ceced3c29ba62c0@95.216.244.235:46656
7ab93b8e2ca45e72c098ae299b911b2a892952ff@85.10.207.173:26656
263e98d6debdd8b28467b8f044134d42cc13a415@86.57.254.202:36656
94b91e86bcfda2583526db9518fc3c02bc84d7a0@93.125.26.210:34656
84b215c3c17bb3c04483ff99d68374613c83f645@93.125.26.210:37656
64f6a89f297742981867ca18231574ec3f12aff8@93.125.26.210:35656

**Comment by Vgk88** [comment]
472d948cf87f5097244dd52482aa7d45167fc96d@176.37.214.146:26656

**Comment by Vgk88** [comment]
96deb450ab5fde55272ae9b8fc83e384b8008c72@176.37.214.146:26656
ecfab61d33d926c33f642c1699b85f86d51d7415@185.117.243.198:26656
98be878d406a3ed931bc9280e19bceec4c27da05@159.224.141.128:26656

**Comment by serejandmyself** [comment]
This is the latest check on seed nodes that i did, was 2 weeks ago:

all other seem to be dead or with a closed port:

"34202f6935503da67c07fd89c59e82a5b588c70f@86.57.138.169:33336, f13a5326886c3e251167d433af12fd531a7bc6ee@88.198.36.117:26656, 263e98d6debdd8b28467b8f044134d42cc13a415@86.57.254.202:36656, 472d948cf87f5097244dd52482aa7d45167fc96d@93.125.26.210:34656, 9b1977e4b1102ce3bedff6d8d0bf2adb90d58b9f@195.201.105.229:26656, b34bcaa7536d0f7e09f775d56ceced3c29ba62c0@95.216.244.235:46656, 7ab93b8e2ca45e72c098ae299b911b2a892952ff@85.10.207.173:26656, 84b215c3c17bb3c04483ff99d68374613c83f645@93.125.26.210:37656"

**Comment by litvintech** [comment]
Closing this, the new iteration will start with Euler-dev and Euler-5 networs
