### ISSUE TITLE
 Exclude at the current stage the consideration of the behavioural factor in the search for ordinary users

### ISSUE THREAD

**Issue by npopeka** [cybercongress/cyberd#327]
In the current version of the protocol, each user by clicking on a link from the a search result connects CiD of key word with the CiD of result content. For example by clicking on "decentralised search"  (IPFS hash QmQd8dLn6V9UETxG9eBNoGb2WB5QsPq7iebiHL9UGkqz2f) user creates a link to https://cyberd.ai/ (IPFS QmQd8dLn6V9UETxG9eBNoGb2WB5QsPq7iebiHL9UGkqz2f).

Analysis of user behavior shows that in most cases, users follow the first 3-7 issue results. If most CYB tokens are owned by regular users, rather than professional participants (validators, content creators, content hosting platforms) who are interested in search quality, then the same results will be at the top of the issue all the time.

![CID_01](https://user-images.githubusercontent.com/29427584/59505832-dfaec900-8ea6-11e9-80fa-8f6bd27d5d21.png)

I suggest at the current stage to position cyberd as a tool for validators and content creators on IPFS indexing, who are interested in content and search quality.

Analysing user behavior and content quality, they index the content with their CYB token balances and store the index on the blockchain. So that it cannot be blocked or censored.

In the future, the behavior of ordinary users will also be taken into account in order to improve search results.

Thus, sending a transaction to the connection of two CIDs should be optional in search UI and carried out only at the user's request with an understanding of what this will lead to.
![cid_02](https://user-images.githubusercontent.com/29427584/59506241-0d484200-8ea8-11e9-9026-674170c4d86f.png)

**Comment by xhipster** [comment]
As far as I understand the possible issue is not in the protocol, but in how it is implemented in frontend application. So closing this issue
