### ISSUE TITLE
Adjust consensus and cyberd params for euler-5

### ISSUE THREAD

**Issue by litvintech** [cybercongress/cyberd#338]
# ://cyberd application params

| Module      | Param         | Value         | Comment                                 |
|-------------|---------------|---------------|-----------------------------------------|
| Staking     | UnbondingTime | 3 days       | time duration of unbonding              |
| Staking     | MaxValidators | 146           | maximum number of active validators set |
| Staking     | MaxEntries    | 7             | max entries for either unbonding delegation or redelegation per delegator/validator pair(delegator/validator/validator for redelegation)|
|             |               |       |                                  |
|             |                  |       |                                 |
| Rank        | RankCalcWindow   | 50   | full rank recalculation window  |
|             |                     |     |                                                                        |
| Distr       | CommunityTax        | 10%  | % block rewards goes to the community pool|
| Distr       | BaseProposerReward  | 1%  | % of block rewards goes to proposer                                  |
| Distr       | BonusProposerReward | 4%  | addition reward, calculated as % of included precommits the proposer includes |
|             |                          |                   |                                                |
| Slashing    | MaxEvidenceAge           | 3weeks            | misbehaviour evidence max age                  |
| Slashing    | SignedBlocksWindow       | 30min             | window to calculate validators liveness        |
| Slashing    | MinSignedPerWindow       | 70%               | min singed precommits for window to not be jailed   |
| Slashing    | DowntimeJailDuration     | 0                 | unjail delay                                   |
| Slashing    | SlashFractionDoubleSign  | 3%               | % of stake reduction for double sign           |
| Slashing    | SlashFractionDowntime    | 0.05%                | % of stake reduction for being offline         |
|             |                          |                   |                              |
| Mint        | Inflation                | need modeling  7% | |
| Mint        | InflationRateChange      | need modeling  13% | |
| Mint        | InflationMax             | need modeling  18% | |
| Mint        | InflationMin             | need modeling  5% | |
| Mint        | GoalBonded               | need modeling 88% | |
| Mint        | BlocksPerYear            | 60 * 60 * 8766 / 5 | Assuming 5 second block times |
|             |                               |                             |                                                            |
| Bandwidth   | RecoveryWindow                | 24h                         | from 0 to max recovery period                              |
| Bandwidth   | PriceSlidingWindow            | 24h                         | price calculated based on network load for selected period |
| Bandwidth   | PriceAdjustWindow             | 1m                          | how ofter price is recalculated                            |
| Bandwidth   | PriceMin                      | 0.01                        | minimum price number (1 means normal price)                |
| Bandwidth   | LinkCost                      | 3* NonLinkCost                         | link msg cost                                              |
| Bandwidth   | NonLinkCost                   | 100               | non link msg cost                                              |
| Bandwidth   | TxCost                        | 2 * LinkCost                | tx cost                                                    |
| Bandwidth   | RecoveryWindowTotalBandwidth  | 4200000000        | how much all users in average can spend for recover period |                                                           |

# ://cyberd consensus params

| Param         | Value         | Comment                                 |
|---------------|---------------|-----------------------------------------|
| MaxBytes      | 1mb   | block max bytes limit            |
| TimeoutPropose | 2s | |
| TimeoutProposeDelta | 500ms | |
| TimeoutPrevote | 1s | |
| TimeoutPrevoteDelta | 500ms | |
| TimeoutPrecommit | 1s | |
| TimeoutPrecommitDelta | 500ms | |
| TimeoutCommit | 1s | |

**Comment by xhipster** [comment]
As we discussed linking must be more expensive than a simple tx because of GPU involvement. So I suppose it must be about twice of simple tx

**Comment by litvintech** [comment]
@xhipster @npopeka @SaveTheAles  please, check proposed by me params and let's discuss this

**Comment by litvintech** [comment]
Closing this now will open new issue closer to Euler-5 genesis
