### ISSUE TITLE
Configure BIP44 path

### ISSUE THREAD

**Issue by litvintech** [cybercongress/cyberd#368]
We need to assign to our chain BIP44 path. Cosmos-SDK allows this for apps to build with.

- [ ] Choose path

- [ ] Register path at SatoshiLab's [slips](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

- [ ] Add path's configuration 

Note: Ledger support apps linked to their paths. So if we define our path we need a stand-alone app for the Ledger. With cosmos native path we have support by default.
Note: There is no convention about paths in cosmos community, [see this](https://github.com/cosmos/cosmos-sdk/pull/4300)
Note: If we going to do this we need to implement a stand-alone import for cosmos addresses in CLI

**Comment by litvintech** [comment]
@xhipster @npopeka please come into the discussion on this

**Comment by litvintech** [comment]
@xhipster @npopeka guys?

**Comment by xhipster** [comment]
I think that using just network prefix is enouth. It would be very useful to have same addresses at least across cosmos networks.
