### ISSUE TITLE
Snapshot of Cosmos Hub for euler-5

### ISSUE THREAD

**Issue by litvintech** [cybercongress/cyberd#369]
Need to make a snapshot of cosmos-hub-2 state in order to form drop in euler-5 and mainnet later.
@mrlp4 Need to launch gaiad node and sync them, better to start from the middle of June backup
QmdQFjRboJAXRNLMZtUfP2gLBSNHVArDYeVmaEHR1Vf4Nw

**Comment by mrlp4** [comment]
Cosmos chain is synced at earth node.
