### ISSUE TITLE
Remove 'cosmosaccaddr' prefix from cyberd address

### ISSUE THREAD

**Issue by arturalbov** [cybercongress/cyberd#39]
For now address looks like: "cosmosaccaddr1mkvg9tpaslgchjuuwck5s6etl8l8nhhy6csn7t"
We should remove 'cosmosaccaddr' prefix from address and leave just hash part.
Address should be "1mkvg9tpaslgchjuuwck5s6etl8l8nhhy6csn7"

**Comment by hleb-albau** [comment]
Not possible yet.
https://github.com/cosmos/cosmos-sdk/issues/1336
Also, changed to cosmos in resent versions

**Comment by hleb-albau** [comment]
@arturalbov now it is possible! https://github.com/cosmos/cosmos-sdk/pull/2614

**Comment by arturalbov** [comment]
@hleb-albau bech32 address cannot have empty prefix so we have to use something instead of `cosmos`
May be it should be something like `cbd` or simply `0x`

**Comment by hleb-albau** [comment]
> @hleb-albau bech32 address cannot have empty prefix so we have to use something instead of `cosmos`
> May be it should be something like `cbd` or simply `0x`

Yeah, '0x' will be cool.

**Comment by xhipster** [comment]
Why not `cyb`?

**Comment by arturalbov** [comment]
> Why not `cyb`?

I think we should choose between `0x` and (`cbd`, `cyb`, `cyberd`, `whatever`). In order for more proper view I'd prefer something like `cyberd` or `cbd`. 
It could be `cyb` but I thought `cyb` prefix is just for browser needs.

**Comment by hleb-albau** [comment]
> Why not `cyb`?

It isn't token, it is address in cyberd, so `cbd` better.
