### ISSUE TITLE
euler-x params discussion

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/cyberd#422]
# Genesis Parameters

## Genesis distribution

| Group                      | value    |Comment                          |
|----------------------------|----------|---------------------------------|
| cosmos gift                |100 TEULs |drop for ~1000000 eth addresses  |
| ethereum gift              |100 TEULs |drop for ~10000 cosmos addresses |
| validators rewards euler-4 |270 TEULS |rewards for euler-4 validation   |
| congress                   |230 TEULs |to congress                      |
| total                      |700 TEULs |                                 |

## Staking Module

| Param             | `devnet`  |Comment                                 |
|-------------------|-----------|----------------------------------------|
| unbonding_time    |24h        |time duration of unbonding              |
| max_validators    |20         |maximum number of active validators set |
| bonded_coin_denom |eul        |the bonded coin denom                   |

## Minting Module

| Param                 | `devnet`            |Comment                                  |
|-----------------------|---------------------|-----------------------------------------|
| inflation             | 0.03                |initial annual inflation rate            |
| inflation_max         | 0.15                |maximum annual inflation rate            |
| inflation_min         | 0.01                |minimum annual inflation rate            |
| inflation_rate_change | 0.13                |rate at which the inflation rate changes |
| goal_bonded           | 0.88                |the point of inflation change sign       |
| blocks_per_year       |6311520 (~5 s/block) |rate at which the inflation rate changes |

## Slashing Module

| Param                      |`devnet`   |Comment                             |
|----------------------------|-----------|------------------------------------|
| max_evidence_age           | 24h       |the maximum age of evidence         |
| signed_blocks_window       | 240       |the rolling window for uptime       |
| min_signed_per_window      | 0.80      |minimum signed blocks in the window |
| downtime_jail_duration     | 0s        |the time before unjail is possible  |
| slash_fraction_double_sign | 0.05      |slashing for double-sign            |
| slash_fraction_downtime    | 0.0001    |slashing for downtime               |

## Distribution Module

| Param                 | `devnet` |Comment                                      |
|-----------------------|----------|---------------------------------------------|
| community_tax         | 0.10     |tax on inflation to community pool           |
| base_proposer_reward  | 0.01     |% of inflation allocated to block proposer   |
| bonus_proposer_reward | 0.05     |% of bonus for block proposer for precommits |
| withdraw_addr_enabled | true     |changing reward withdrawal addresses         |

## Governance Module

| Param              | `devnet`     |Comment                                                          |
|--------------------|--------------|-----------------------------------------------------------------|
| min_deposit        | 70 GEULs     |the minimum deposit to bring a proposal up for a vote            |
| max_deposit_period | 24h          |the duration in which a proposal can collect deposits            |
| voting_period      | 24h          |the duration in which a proposal can be voted upon               |
| quorum             | 0.334        |a minimum quorum of 40% of bonded stake must vote on a proposal  |
| threshold          | 0.500        |over half the voting stake must vote in favor of a proposal      |
| veto               | 0.334        | 1/3 of voting stake vetoing a proposal prevents it from passing |

## Bandwidth Module

| Param               | `devnet`     |Comment                                                          |
|---------------------|--------------|-----------------------------------------------------------------|
| recovery_period     | 24h          |from 0 to max recovery period                                    |
| adjust_price_period | 100s         |how ofter price is recalculated                                  |
| base_credit_price   | 1.0          |a minimum quorum of 40% of bonded stake must vote on a proposal  |
| desirable_bandwidth | 200000000    |over half the voting stake must vote in favor of a proposal      |
| max_block_bandwidth | 111111       | 1/3 of voting stake vetoing a proposal prevents it from passing |
| link_msg_cost       | 1000         |the minimum deposit to bring a proposal up for a vote            |
| tx_cost             | 300          | 1/3 of voting stake vetoing a proposal prevents it from passing |
| non_link_msg_cost   | 500          | 1/3 of voting stake vetoing a proposal prevents it from passing |

## Rank Module

| Param               | `devnet`     |Comment                                                   |
|---------------------|--------------|----------------------------------------------------------|
| calculation_period  | 25s          |the number of blocks defined for graph full recalculation |
| damping_factor      | 0.85         |                                                          |
| tolerance           | 0.0001       |                                                          |

**Comment by SaveTheAles** [comment]
seed CIDs for genesis:

**rankformula**
QmRWaKCshJKS6owThqrptydmvAKHQMnhea7rdUtfKpbALQ   ->   QmSCdv7v7w24nu9rTKhEC2NxQjCf4FXcfFj1sGBGUoCUMi

**eulerrewards**
QmXSDghYn9EHNktdhqKnC52JZL12oWdQodZDP3o85syvNM   ->   Qmd2HFHVY2LdNACrVk54rVgaPWsMJ8J73hNfQW3PGDwH44

**cosmosgift**
QmTwVmWXsDJhJEpwTe3R7nk8C5DLz5tozETWwCyPRZL6Ch   ->   QmcjeTciMNgEBe4xXvEaA4TQtwTRkXucx7DmKWViXSmX7m

**ethereumgift**
QmZdRefYuk197Pbb9MmFz646vjMPFPM9DKrMTjhBqzNDrk   ->   QmcjeTciMNgEBe4xXvEaA4TQtwTRkXucx7DmKWViXSmX7m

**cyberpaper**
QmVx2aMGLFPQ9hoQFWw7e1LYcp9nmaUKLFkuRXnK2gLgWv   ->   QmTHdKN4yY1VfeekGZd2cunmeRP5Vubx3Cq8yPe6gZ1S32

**cyber**
QmRX8qYgeZoYM3M5zzQaWEpVFdpin6FvVXvp6RPQK3oufV   ->   QmRWaKCshJKS6owThqrptydmvAKHQMnhea7rdUtfKpbALQ, QmXSDghYn9EHNktdhqKnC52JZL12oWdQodZDP3o85syvNM, QmTwVmWXsDJhJEpwTe3R7nk8C5DLz5tozETWwCyPRZL6Ch, QmZdRefYuk197Pbb9MmFz646vjMPFPM9DKrMTjhBqzNDrk, QmVx2aMGLFPQ9hoQFWw7e1LYcp9nmaUKLFkuRXnK2gLgWv

**Comment by serejandmyself** [comment]
@litvintech

Generally speaking, I have questions regarding a few, but it would be best if you pointed me in the right directions on what needs to be discussed.
Is the question technical or concerning the size / amount of the params?

**Comment by litvintech** [comment]
@serejandmyself Its about parameters values. We launched euler-dev chain with this setup

**Comment by litvintech** [comment]
@SaveTheAles Please update table with actual params
