### ISSUE TITLE
Add instructions for easy install and use non-validating version of cyberdcli

### ISSUE THREAD

**Issue by xhipster** [cybercongress/cyberd#425]
## User Story

As advanced agent I want to have ability to build cyberd from sources without bells and whistles and have ability to work with keys and transactions without necessity to load and validate all blockchain 

## Why Is this Needed?

Because  not all agent must validate the blockchain in order to use it

## Definition of Done
- instruction is updated in the /docs folder
- short version of instruction in README.md

**Comment by litvintech** [comment]
Updated README with
