### ISSUE TITLE
Command list from euler 3 update

### ISSUE THREAD

**Issue by serejandmyself** [cybercongress/cyberd#433]
Commands for using node from CLI needs updating per devnet:
Cyb - Eul
Testnet version
linking hashes, etc 
(basically, just add specification to guides)

**Comment by litvintech** [comment]
@mrlp4 please help @serejandmyself deal with this

**Comment by mrlp4** [comment]
There's also couple commands changed themself, just necessary to take old guide and try every single command with new chain.

**Comment by litvintech** [comment]
@mrlp4 can you close this?

**Comment by mrlp4** [comment]
All checked.
