### ISSUE TITLE
Error in RPC response, top endpoint

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/cyberd#451]
### Current Behavior
top 31 CID not responding
https://titan.cybernode.ai/api/top?page=%2230%22&perPage=%221%22

```json
{
   "jsonrpc": "2.0",
   "id": "",
   "error": {
                 "code": -32603,
                 "message": "Internal error",
                 "data": "Error marshalling response: json: unsupported value: NaN"
   }
}
```

### Expected Behavior
would love to know data of 31 top CID

**Comment by litvintech** [comment]
@SaveTheAles error references to NaN values of objects rank #455 
Going to remove this values from sorting and top1000 list
