### ISSUE TITLE
Define distribution in paper

### ISSUE THREAD

**Issue by xhipster** [cybercongress/cyberd#5]

**Comment by hleb-albau** [comment]
@xhipster Still actual?

**Comment by xhipster** [comment]
Yes. Working on it right now

**Comment by xhipster** [comment]
A new structure approved by a congress
<img width="400" alt="screenshot 2018-12-11 at 01 19 57" src="https://user-images.githubusercontent.com/410789/49767989-53e39680-fce3-11e8-88c7-b6cc4f88d67d.png">

**Comment by hleb-albau** [comment]
@xhipster we can close it, true?
