### ISSUE TITLE
Genesis state generator

### ISSUE THREAD

**Issue by xhipster** [cybercongress/cyberd#92]
Must be based on spring rang calculated from fresh Ethereum state

**Comment by hleb-albau** [comment]
@belya Is it possible to pack all your work into script calculating genesis file? Thus every one can verify/generate our genesis.

**Comment by belya** [comment]
@hleb-albau 
1. 

Yes, it is quite possible. We can pack database filling script with spring rank calculations and a procedure of addresses filtering inside a docker container, so everyone can use it. But could you describe genesis verification process in details? 

Do you want to check statistical significance of calculated ranks? If yes, is it possible to wait a little bit while we are preparing cross-validation procedures? Cause the accuracy value can show more than just a quick look at the full list of addresses.

2. 

Of course! Waiting for the link to the dedicated repo :)

**Comment by xhipster** [comment]
I think this is also done
