### ISSUE TITLE
Get rid of RPC proxy

### ISSUE THREAD

**Issue by arturalbov** [cybercongress/cyberd#94]
Get rid of RPC proxy.
Find a way to binary marshal transactions on client side.
Possible solution: https://github.com/TanNgocDo/Js-Amino

**Comment by hleb-albau** [comment]
Use custom tx decoder.

**Comment by arturalbov** [comment]
Blocked by https://github.com/cosmos/cosmos-sdk/pull/2959

**Comment by arturalbov** [comment]
Json marshaled structure weights 4x more times compare to binary marshaled. It is not the way we need.
The only way to binary marshal transaction in Go now is go-amino. As our js client cannot marshal transactions in way go-amino does, we have to wait for js-amino implementation or write our own solution on both sides (that'll take huge amount of time). Closed till better times.
